:PROPERTIES:
:ROAM_REFS: [cite:@alexanderThenHighSaturatedFatDiets2020]
:ID:       4737f7a9-faec-4d2c-a901-227495ab0373
:DIR:      /usr/local/google/home/cashweaver/proj/roam/attachments/4737f7a9-faec-4d2c-a901-227495ab0373
:END:
#+title: Scott Alexander | For, Then Against, High-Saturated-Fat Diets
#+author: Cash Weaver
#+date: [2022-02-06 Sun 17:33]
#+filetags: :reference:
 
[[id:e7e4bd59-fa63-49a8-bfca-6c767d1c2330][Scott Alexander]], [cite:@alexanderThenHighSaturatedFatDiets2020]

* Summary

Discussion, without firm conclusion, regarding the source of the American obesity epidemic.

* Thoughts

** Perfectionism

A sentence in the beginning of the essay stood out to me:

#+begin_quote
I've been told that another blog called Hyperlipid has a deeper investigation, but I've only scratched the surface of them. [...] I don't claim to fully understand these people and I apologize for any misrepresentations I might be making. But the short version is: they all agree that everything went wrong when we switched from saturated to unsaturated fat.
#+end_quote

It stands out because Scott specifically mentions the edge of his research and yet published the piece anyway. There is a loud voice in the back of my head whenever I'm writing anything "original" which drives me to go deeper and that stones left unturned will mar my writing. I wouldn't recommend anyone to actually /listen/ to this voice but it's damn loud and I'm glad to see a concrete example of someone ignoring it.

** "Processed" Food

#+begin_quote
What food counts as "processed" or "not processed"?
#+end_quote

I found myself nodding along to this paragraph as I read. I've had the same thought with the same (inferred) sense of exasperation.

* Notes

#+begin_quote
In the 1800s, the average US man [[https://voxeu.org/article/100-years-us-obesity][weighed about]] 155 lbs. Today, he weighs about 195. The change is even starker at the extremes. Someone at the 90th percentile of weight back then weighed about 185 lbs; today, he would weigh 320 lbs. Back then, [[https://www.econstor.eu/bitstream/10419/80491/1/cesifo_wp4366.pdf][about 1%]] of men were obese. Today, about 25% are.
#+end_quote

#+begin_quote
The answer to all these questions seems to be something like "the body is pretty good at regulating its own weight under any diet except modern American processed food." But what aspect of processed food makes it bad?
#+end_quote

#+begin_quote
The only common villain everyone agrees on in the obesity story is "processed food". I've previously found this frustrating – it reeks of a sort of unreflective technophobia. What part of processing makes food bad? How does mere contact with a machine turn food from healthy to unhealthy? What food counts as "processed" or "not processed"? Is ground beef processed, since you grind it? Are scrambled eggs processed, since you scramble them? Is bread processed, since wheat doesn't grow in loaves? Is water processed, since it goes through water processing facilities? Is the Eucharist processed, even though the processing only changes its metaphysical essence and not its physical properties? Everybody I ask acts like the answers to these questions are obvious, but everyone has different answers, and nobody can tell me their decision procedure.
#+end_quote

#+print_bibliography:

* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:



