:PROPERTIES:
:ID:       2667c79c-7b48-424c-ba91-d0ace144a86c
:DIR:      /home/cashweaver/proj/roam/attachments/2667c79c-7b48-424c-ba91-d0ace144a86c
:ROAM_REFS: https://news.ycombinator.com/item?id=22325975
:END:
#+TITLE: Ask HN: How do you learn complex, dense technical information?
#+hugo_custom_front_matter: roam_refs '("https://news.ycombinator.com/item?id=22325975")
#+STARTUP: overview
#+AUTHOR: Cash Weaver
#+DATE: [2021-12-30 Thu 12:41]
#+HUGO_AUTO_SET_LASTMOD: t

* Notes

#+begin_quote
Essentially I think learning is fundamentally Pain. You have to take on the pain before the learning can alleviate it, if you try to skip the pain then you have only a superficial idea of what you're talking about.

[[https://news.ycombinator.com/item?id=22327554][crdrost]]
#+end_quote

#+begin_quote
Interestingly there is a concept in learning research called "[[id:89eb6adc-d8f8-4033-bc46-7fed725c3c01][desirable difficulty]]". The idea is that learning something, forgetting it and then struggling to learn it again leads to faster learning times. It may be that struggle is inherent in the process of learning something complex. If you equate struggle with pain, then I think it makes some sense.

[[https://news.ycombinator.com/item?id=22330631][mikekchar]]
#+end_quote

#+begin_quote
In my ~20 years of experience, the only way to get good at something that is incredibly complex like kernel development, you will need to actually try to build the thing. Over and over and over.

[[https://news.ycombinator.com/item?id=22330078][bob1029]]
#+end_quote

#+begin_quote
In the language learning example, Extensive Reading leads to not only picking up and remembering words, but also collocations, grammar and even cultural beliefs of the speakers of the target language. Single word flash cards miss all of that. Full sentence flashcards do a bit better but still fall short.

I think the best use for SRS for something like a language or programming is for laying down a scaffold in the very early stages of learning, and then moving to more productive uses of study time as soon as possible.

[[https://news.ycombinator.com/item?id=22332329][AlchemistCamp]], replying to [[https://news.ycombinator.com/item?id=22326925][stared]]
#+end_quote

This raises an important point in the use of spaced repetition systems (SRS). I wouldn't expect someone to be able to write a good essay if they only studied the meaning of words. Spaced repetition systems lend themselves easily to the study of small chunks of information (eg: definitions) but it is more difficult to apply them to higher-level applications of knowledge and understanding (eg: essay writing).

#+begin_quote
I think semantic tree/first principles/physics-based approach (popularly attributed to Elon Musk) is one way to approach it. It's actually a really difficult approach and you need a certain level of intelligence and personality to do it well, so it's not for everyone. I can do it to some extent but it's actually really difficult to hold lots of ideas in tension and to be questioning all the time -- it's just not my thinking style.

The other approach is what many smart (but non-geniuses) take: the buffet approach. You graze at the table of books, Wikipedia, online articles, and hang out in online communities (like Twitter) to overhear what experts are discussing. The thing about most areas of knowledge is, there's usually only 20% of the subject that matters--the rest rarely come up (Pareto Principle). To know what 20% to focus on, you need to understand the sociology of the subject matter and what experts think are important. Unlike the previous approach, you won't have watershed-level insights, but you'll know enough to be considered "educated" on the subject.

[[https://news.ycombinator.com/item?id=22327704][wenc]]
#+end_quote


* Thoughts
:PROPERTIES:
:ID:       0c2543e9-cbf9-4324-b9c2-ecbc8109b18c
:END:
Relevant: [[id:e6b1cd50-8293-44a3-bcba-d302d0835470][How to Read a Paper]]
