:PROPERTIES:
:ID:       b37a4585-be03-43ea-a55c-6a5f84e59c77
:END:
#+title: Atom
#+author: Cash Weaver
#+date: [2022-06-29 Wed 08:31]
#+filetags: :concept:
An atom, in [[id:f6e9082b-3589-448a-9877-b9a2b31d88ba][Lisp]], is an indivisible thing. Examples include:

- Numbers (e.g. =12=)
- Strings (e.g. =foo=)
- Symbols (e.g. =+= or ='pi=)

#+begin_quote
This term comes from the historical meaning of the word atom, which means "indivisible". As far as Lisp is concerned, the words we have been using in the lists cannot be divided into any smaller parts and still mean the same thing as part of a program; likewise with numbers and single character symbols like '+'. On the other hand, unlike an ancient atom, a list can be split into parts.

[...]

Technically speaking, a list in Lisp consists of parentheses surrounding atoms separated by whitespace or surrounding other lists or surrounding both atoms and other lists. A list can have just one atom in it or have nothing in it at all. A list with nothing in it looks like this: (), and is called the empty list. Unlike anything else, an empty list is considered both an atom and a list at the same time.

[cite:@LispAtomsa]
#+end_quote

#+print_bibliography:
* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:
** [[id:b37a4585-be03-43ea-a55c-6a5f84e59c77][Atom]]
:PROPERTIES:
:ANKI_DECK: Default
:ANKI_NOTE_TYPE: Definition
:ANKI_NOTE_ID: 1656857175760
:END:
*** Context
[[id:f6e9082b-3589-448a-9877-b9a2b31d88ba][Lisp]]
*** Definition
Everything that isn't a list; an indivisible thing. Examples include numbers, strings, symbols, etc.
*** Extra
*** Source
[cite:@LispAtomsa]
