:PROPERTIES:
:ID:       b94aacf3-1c11-42da-a39b-47de9892bd7b
:DIR:      /home/cashweaver/proj/roam/attachments/b94aacf3-1c11-42da-a39b-47de9892bd7b
:ROAM_REFS: https://www.benkuhn.net/attention/
:END:
#+title: Attention is Your Scarcest Resource
#+hugo_custom_front_matter: roam_refs '("https://www.benkuhn.net/attention/")
#+filetags: :@Ben_Kuhn:attention:meta-work:
#+author: Cash Weaver
#+date: [2021-12-03 Fri 11:46]
#+startup: overview
#+hugo_auto_set_lastmod: t

* Notes

#+begin_quote
The output of knowledge workers is extremely skewed based on focus. The productivity tiers seem to be:

- <10% focused on the job at hand: meaningful risk of getting fired.
- 10-50% focus: “meets expectations,” gets regular raises.
- 50%+ focus: superstar, 10x engineer, destined for greatness.

/[[https://www.thediff.co/p/the-future-of-remote-work-is-not][Byrne Hobart]]/
#+end_quote

#+begin_quote
“50%+ focus” is roughly when something becomes the top idea in your mind. It’s when you start caring enough to think about it in the shower. It’s when you start habitually asking “how could this go faster?” It’s when you get relentlessly resourceful. It’s around when you start annoying your coworkers and/or significant other, although that part is avoidable with practice.

Most importantly, you can only be 50%+-focused on one thing at a time—or zero, in bad cases. That makes it critical to conserve your attention, so that you can spend it on what matters.
#+end_quote

#+begin_quote
As a programmer, I tried to make sure that I was only ever working on one thing at a time. Even if I got stuck on that one thing—say I was blocked on waiting for a tech partner to give me API documentation—I’d let myself stay stuck instead of sliding off to work on something else.

In the short term, this made me less efficient, because I’d spend less time programming and more time staring vacantly at the ceiling. But if I stared vacantly for long enough, I’d eventually get mad enough to, e.g., reverse-engineer the partner’s API in a fit of rage. This resulted in me shipping my most important projects faster, hence getting faster compounding growth.
#+end_quote
