:PROPERTIES:
:ID:       e0b22ae5-2b52-4433-8282-ad86037915d4
:END:
#+title: Avoidant attachment
#+author: Cash Weaver
#+date: [2022-06-26 Sun 13:22]
#+filetags: :concept:

An [[id:5f944538-ef8c-464f-b2da-c0f973558eca][attachment]] pattern in which the child "gives up" on receiving comfort altogether.

#+begin_quote
An infant with an anxious-avoidant pattern of attachment will avoid or ignore the caregiver—showing little emotion when the caregiver departs or returns. The infant will not explore very much regardless of who is there. Infants classified as anxious-avoidant (A) represented a puzzle in the early 1970s. They did not exhibit distress on separation, and either ignored the caregiver on their return (A1 subtype) or showed some tendency to approach together with some tendency to ignore or turn away from the caregiver (A2 subtype). Ainsworth and Bell theorized that the apparently unruffled behaviour of the avoidant infants was in fact a mask for distress, a hypothesis later evidenced through studies of the heart-rate of avoidant infants.

[...]

Main proposed that avoidance has two functions for an infant whose caregiver is consistently unresponsive to their needs. Firstly, avoidant behaviour allows the infant to maintain a conditional proximity with the caregiver: close enough to maintain protection, but distant enough to avoid rebuff. Secondly, the cognitive processes organising avoidant behaviour could help direct attention away from the unfulfilled desire for closeness with the caregiver—avoiding a situation in which the child is overwhelmed with emotion ("disorganized distress"), and therefore unable to maintain control of themselves and achieve even conditional proximity.

[cite:@AttachmentTheory2022]
#+end_quote

#+print_bibliography:
* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:

** Avoidant attachment
:PROPERTIES:
:ANKI_DECK: Default
:ANKI_NOTE_TYPE: Describe
:ANKI_NOTE_ID: 1656857252534
:END:

*** Context
Attachment theory

*** Description
An unhealthy attachment pattern in which the child "gives up" on receiving comfort from their guardian(s) and instead attempts to distance themselves emotionally; go it alone and become distrustful of interpersonal relationships.

*** Extra

*** Source
[cite:@AttachmentTheory2022]

** Avoidant attachment
:PROPERTIES:
:ANKI_NOTE_TYPE: Example(s)
:ANKI_NOTE_ID: 1656857253108
:END:

*** Example(s)
- A neglected or abused child seeking to distance themselves from their guardians.

*** Extra

*** Source
[cite:@AttachmentTheory2022]




