:PROPERTIES:
:ID:       065a0303-c2d3-40a0-a8fb-793f19f02526
:END:
#+title: Branch book
#+author: Cash Weaver
#+date: [2022-07-17 Sun 09:50]
#+filetags: :concept:

#+begin_quote
Branch books are the most common type of book you'll find in the non-fiction section. These are books that consist of a single idea. The rest of the book is then padded out with examples, extrapolations, and implications of that single idea. A good example of this is Nicholas Nassem Taleb's Antifragile, which can be summarised in a single sentence: "the world consists of systems that are fragile (break easily), robust (are difficult to break) and are antifragile (gets stronger the more you try to break it e.g. like democracy)." The rest of the book explores the full implications of seeing systems as 'fragile/robust/antifragile'.

[cite:@chinThreeKindsNonfiction2018]
#+end_quote
#+print_bibliography:
* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:

** Branch books
:PROPERTIES:
:ANKI_NOTE_TYPE: Definition
:ANKI_NOTE_ID: 1640627828297
:END:

*** Context
[[id:4c9b1bbf-2a4b-43fa-a266-b559c018d80e][Cedric Chin]]
*** Definition
Books which consist of a single idea which is padded out with examples, extrapolations, and implications.
*** Extra
*** Source
https://commoncog.com/blog/the-3-kinds-of-non-fiction-book/#branchbooks
