:PROPERTIES:
:ROAM_REFS: [cite:@chinThreeKindsNonfiction2018]
:ID:       ee7ed2c5-dd15-42aa-8cfe-8149ce58473e
:DIR:      /home/cashweaver/proj/roam/attachments/ee7ed2c5-dd15-42aa-8cfe-8149ce58473e
:END:
#+title: Cedric Chin | The Three Kinds of Non-Fiction Books
#+author: Cash Weaver
#+date: [2022-02-07 Mon 07:36]
#+filetags: :reference:
#+hugo_auto_set_lastmod: t
 
[[id:4c9b1bbf-2a4b-43fa-a266-b559c018d80e][Cedric Chin]], [cite:@chinThreeKindsNonfiction2018]

* Summary
* Thoughts
* Notes
** Narrative

#+begin_quote
Narrative books are books that tell a story. Examples include biographies, memoirs, and histories.
#+end_quote

** Tree

#+begin_quote
Tree books are books that lay out a framework of ideas. A good example is Daniel Kahneman's Thinking: Fast and Slow, which lays out his life's work — the entirety of behavioural economics — in a single book. (So an entire field, like a tree of knowledge, in one book. Geddit, geddit?) Other books I can think of in this category are High Output Management by Andy Grove, and Principles by Ray Dalio.
#+end_quote

** Branch

#+begin_quote
Branch books are the most common type of book you'll find in the non-fiction section. These are books that consist of a single idea. The rest of the book is then padded out with examples, extrapolations, and implications of that single idea. A good example of this is Nicholas Nassem Taleb's Antifragile, which can be summarised in a single sentence: "the world consists of systems that are fragile (break easily), robust (are difficult to break) and are antifragile (gets stronger the more you try to break it e.g. like democracy)." The rest of the book explores the full implications of seeing systems as 'fragile/robust/antifragile'.
#+end_quote

* TODO Create individual concept nodes?

Maybe something more general, like novel conceptual density in writing.
#+print_bibliography:
