:PROPERTIES:
:ID:       4d921d58-fc30-4584-8863-b53707cdbe48
:DIR:      /home/cashweaver/proj/roam/attachments/4d921d58-fc30-4584-8863-b53707cdbe48
:ROAM_REFS: https://www.greaterwrong.com/posts/yFALNnscB2qgehnJv/deregulating-distraction-moving-towards-the-goal-and-level
:END:
#+title: Deregulating Distraction, Moving Towards the Goal, and Level Hopping
#+filetags: :@So8res:
#+author: Cash Weaver
#+date: [2021-12-03 Fri 12:24]
#+startup: overview
#+hugo_auto_set_lastmod: t

#+begin_quote
I started doing NaNoWriMo in 2011, and I noticed something interesting: a vast majority of winners barely made it to 50,000 words. The goal of NaNoWriMo is to write 50k words in a month, so I wasn’t particularly surprised. However, from my interactions with others I found that a vast majority of these winners felt like they were pushing themselves to the limit, even though many of them were probably psychologically anchored below their actual limits. After all, in my experience, the hardest part of NaNoWriMo is writing every day: the most difficult part of being productive is switching contexts, once you get rolling it’s not difficult to keep rolling.

It seemed clear that if the goal had been 60k, many of the same people would have eeked out a victory with similar margins and the same narrative of butting against their limits. The natural conclusion was that I can’t trust myself to feel out my own limits.
#+end_quote
