:PROPERTIES:
:ID:       89eb6adc-d8f8-4033-bc46-7fed725c3c01
:DIR:      /home/cashweaver/proj/roam/attachments/89eb6adc-d8f8-4033-bc46-7fed725c3c01
:ROAM_REFS: https://en.wikipedia.org/wiki/Desirable_difficulty
:END:
#+title: Desirable Difficulty
#+hugo_custom_front_matter: roam_refs '("https://en.wikipedia.org/wiki/Desirable_difficulty")
#+author: Cash Weaver
#+date: [2021-12-30 Thu 15:13]
#+startup: overview
#+hugo_auto_set_lastmod: t

#+begin_quote
A desirable difficulty is a learning task that requires a considerable but desirable amount of effort, thereby improving long-term performance.
#+end_quote

Examples include:

1. Retrieval practice (eg: flashcards)
2. [[id:37699e33-fccb-43bf-ab4b-ca9e74a03510][Spacing]] and interleaving (eg: [[id:a72eecfc-c64a-438a-ae26-d18c5725cd5c][Spaced Repetition]])

#+begin_quote
To determine whether a difficulty is desirable, use the following three guidelines:

1. The processing at encoding should be the same as the processing at retrieval.
2. The processing at encoding should be the same as the processing during practice.
3. The task must be able to be accomplished. Too difficult a task may dissuade the learner and prevent full processing.

TODO
#+end_quote

* TODO Include direct quote from Memory in Educational Settings by Marsh and Butler, as they're quoted in the wikipedia page.
