:PROPERTIES:
:ROAM_REFS: [cite:@matuschakKnowledgeWorkShouldAccrete]
:ID:       3abdd6f0-2229-4f83-a0ac-078af4571f8c
:DIR:      /home/cashweaver/proj/roam/attachments/3abdd6f0-2229-4f83-a0ac-078af4571f8c
:END:
#+title: Andy Matuschak | Knowledge Work Should Accrete
#+author: Cash Weaver
#+date: [2022-02-11 Fri 20:02]
#+startup: overview
#+filetags: :reference:
#+hugo_auto_set_lastmod: t
 
[[id:df479fb9-f7b0-4e3a-a7eb-41849fbc190e][Andy Matuschak]], [cite:@matuschakKnowledgeWorkShouldAccrete]

#+begin_quote
Many activities in Knowledge work seem to be ephemeral efforts, their outputs mostly discarded after they’re completed.

You might wake up to a really tricky email and realize that it connects to something you’ve been thinking about for a while. You might spend an hour writing a careful reply, capturing your latest thinking. And now… it lives in your “sent” folder, and briefly in the impression on your and your colleague’s mind. The effort accumulates only insofar as that work subtly influences your and your colleague’s thinking over time.

Likewise, Most people take only transient notes, though with effective practices, they’re an essential foundation; see Evergreen note-writing as fundamental unit of knowledge work.

We should strive to design practices systems which yield compounding returns on our efforts as they accumulate over time.

A Spaced repetition memory system achieves this for memory: when you find information useful, you can invest a little effort to make sure you always have it available. Over time, one’s spaced repetition library accumulates thousands of questions, and (I strongly suspect) that knowledge makes it easier to be an effective knowledge worker later.
#+end_quote

#+print_bibliography:
