:PROPERTIES:
:ROAM_REFS: [cite:@kuenzliKeyPracticesAchievingLargeProfessionalGoals2019]
:ID:       3e7f1498-0d7c-4794-99c3-c22d6e316c52
:DIR:      /home/cashweaver/proj/roam/attachments/3e7f1498-0d7c-4794-99c3-c22d6e316c52
:END:
#+title: Stephen Kuenzli | Key Practices for Achieving Large Professional Goals
#+author: Cash Weaver
#+date: [2022-02-06 Sun 20:49]
#+filetags: :reference:
 
[[id:5a7ebf66-7622-47b1-9778-91cbb4566561][Stephen Kuenzli]], [cite:@kuenzliKeyPracticesAchievingLargeProfessionalGoals2019]

* Summary

#+begin_quote
I attribute much of my success in 2019 to the practices of:

1. writing to develop my thoughts
2. learning to focus
#+end_quote

#+begin_quote
I wrote a lot in 2019 ... This practice of writing resulted in a couple major changes:

1. I now use writing as a primary mechanism to develop my thoughts on a subject
2. Writing is now a healthy habit for my professional skills and business
#+end_quote

Kuenzli mentions that they "really learned how to focus and extract much more value out of the time I have available". They specifically call attention to four ways they pursued [[id:82d1d3b6-dd55-43bf-828e-b34508ac136c][Deep Work]]:

1. Removing social media from their daily routine

   #+begin_quote
Two 'surprising' things happened when I reduced the Twitter app timer limit to 30 then 5 minutes:

1. I didn't miss it
2. My stress level dropped and mood improved significantly
   #+end_quote

2. Scheduling their work day using pen and paper
3. Scheduling important work for the beginning of the day

   #+begin_quote
It's only possible to work at peak levels sustainably for 3-4 hours per day. So, I pack writing, product management, product development, and planning into the morning. The most creative and intense work of the day is usually done by the time I go to lunch.
   #+end_quote

4. Wrapping up work in preparation for the next day

   #+begin_quote
At 15 minutes to 5, I start getting my work to a good stopping point, check my email for urgent issues, then I say this mantra out loud to recognize myself for the day's efforts and combat my perfectionist, always on tendencies:

"That's good for today."
   #+end_quote

* Thoughts

I've added an "End the Day" event to my calendar for the last 15 minutes of the day.

* Notes
#+print_bibliography:

* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:


