:PROPERTIES:
:ROAM_REFS: [cite:@mooredsCultivateSkillUndividedAttentionDeepWork2019]
:ID:       86dde162-154f-49fb-98a9-41dddcf60ecb
:DIR:      /usr/local/google/home/cashweaver/proj/roam/attachments/86dde162-154f-49fb-98a9-41dddcf60ecb
:ROAM_REFS: https://letterstoanewdeveloper.com/2019/12/19/cultivate-the-skill-of-undivided-attention-or-deep-work/
:END:
#+title:  Dan Moore | Cultivate the Skill of Undivided Attention, or "Deep Work"
#+hugo_custom_front_matter: roam_refs '("https://letterstoanewdeveloper.com/2019/12/19/cultivate-the-skill-of-undivided-attention-or-deep-work/")
#+author: Cash Weaver
#+date: [2022-02-06 Sun 16:00]
#+startup: overview
#+filetags: :reference:
#+hugo_auto_set_lastmod: t
 
[[id:8c414004-a945-4c4b-a374-ab35a73383fb][Dan Moore]], [cite:@mooredsCultivateSkillUndividedAttentionDeepWork2019]

* Summary
* Thoughts
* Notes

#+begin_quote
Here’s the list of topics that I’d need to dedicate significant time to, in order to close the gap between me and the senior developers on our team, that I’ve encountered in my last two days of work:

- Breaking complex unknowns into simpler unknowns that can be further split into individual tickets
- Adding tests to complex, legacy code, to guide further refactoring of said code.
- Using =grep= to comb through server logs to diagnose a hard-to-identify-and-reproduce problem
- Provisioning new servers
- Building bash scripts to automate complex workflows
- Digging into gem source code to can shed gem dependencies while maintaining certain features
- Understanding indexing well enough to see that certain queries that we thought were using indexes were not, and fix this oversight index on the fly, without causing any blips in availability
#+end_quote

#+begin_quote
We should not target improving lagging indicators, we should improve leading indicators.
#+end_quote

#+begin_quote
Rather than focusing on a list of things other developers have learned, and targeting that list, I humbly propose that a leading indicator of acquiring this kind of knowledge is "hours per week spent in a state of intentional [[id:82d1d3b6-dd55-43bf-828e-b34508ac136c][deep work]]".
#+end_quote

#+begin_quote
Do more deep work, and over a year or two years, your skills will grow much faster than those doing less deep work. Eventually, you might find that you’re doing the work of a senior developer!
#+end_quote

#+print_bibliography:
