:PROPERTIES:
:ID:       3a48cc59-c9e7-4253-bbf0-8d52622c71c0
:DIR:      /home/cashweaver/proj/roam/attachments/3a48cc59-c9e7-4253-bbf0-8d52622c71c0
:ROAM_REFS: https://www.lesswrong.com/posts/KwdcMts8P8hacqwrX/noticing-the-taste-of-lotus
:END:
#+title: Noticing the Taste of Lotus
#+hugo_custom_front_matter: roam_refs '("https://www.lesswrong.com/posts/KwdcMts8P8hacqwrX/noticing-the-taste-of-lotus")
#+filetags: :@Valentine:@Michael_Smith:
#+author: Cash Weaver
#+date: [2021-12-03 Fri 12:30]
#+startup: overview
#+hugo_auto_set_lastmod: t

#+begin_quote
Duncan Sabien sometimes talks about “lotus-eating”. He’s referring to a [[https://en.wikipedia.org/wiki/Lotus-eaters][part of the Odyssey where they land on an island of “lotus-eaters”]]. It turns out that once you eat some of this kind of lotus, all you want to do is eat more. You stop caring about your other goals. The lotus just grabs your wants directly.
#+end_quote

The idea of noticing the taste of lotus is closely related to mindfulness and attention.

Valentine wrote a [[https://www.lesswrong.com/posts/KwdcMts8P8hacqwrX/noticing-the-taste-of-lotus?commentId=3buxF2Wk45a7QYLM2][follow-up review]] in which he emphasized the specific claims he made in his original article:

#+begin_quote
1. External forces can shape what we want to do. (I.e., there are lotuses.)
2. It's possible to notice this in real time. (I.e., you can notice the taste of lotuses.)
3. It's good to do so. Otherwise we find our wanting aligned with others' goals regardless of how they relate to our own.
4. If you notice this, you'll find yourself wanting to spit out lotuses that you can tell pull you away from your goals.

[[https://www.lesswrong.com/posts/KwdcMts8P8hacqwrX/noticing-the-taste-of-lotus?commentId=3buxF2Wk45a7QYLM2][Valentine]]
#+end_quote

I like this way of breaking a piece of writing apart into claims. Doing so reminds me of breaking a commit down into small, independent, chunks and all the benefits that come with that practice. There's a balancing act between leveraging links to other, single-purpose, writing throughout a piece and writing a monolithic entry which can be taken as is without further context or external references.

As for the claims themselves, I identify with the way the author has phrased claim #3. I find myself at the precipice of rabbit holes regularly with regard to video games. Factorio, for example, is a game that I enjoyed playing so much that I had to cut myself off from it. I would find myself thinking about my factory, and future factories, throughout the day. The optimization problems were enchanting and satisfied a need to accomplish and be productive so well that I dropped a lot of other goals/etc and replaced them, for a time, with Factorio. It's not that Factorio is bad -- it's a fantastic game -- but that I discover, after coming out of the haze of hours and hours of perfecting resource gathering, delivery, and processing, that I've realigned my goals around the game and that those new goals won't take me where I want to go.

* TODO Convert to citation through Zotero
