:PROPERTIES:
:ID:       4398317e-6aa1-4dd4-b2a5-6334256ca2cc
:DIR:      /home/cashweaver/proj/roam/attachments/4398317e-6aa1-4dd4-b2a5-6334256ca2cc
:END:
#+title: Play to Win
#+author: Cash Weaver
#+date: [2022-02-16 Wed 19:22]
#+filetags: :concept:

* TODO

- https://commoncog.com/blog/playing-to-play-playing-to-win/
- https://news.ycombinator.com/item?id=28608436
- [[id:e02451fc-c9d5-4c02-849b-d9b7d4cc95a7][Derek Sivers | There's No Speed Limit]]
- https://www.sirlin.net/articles/playing-to-win
- Greedy algorithms
- Local, rather than global, maxima
- Unwritten rules or, perhaps another way of stating it, the penumbra of the rule set
- As an extension: Play to win doesn't have to imply that you're trying to win for winning's sake. It is also reasonable to incorporate play to win strategies to serve a larger goal -- a goal that you set. Play to win strategies do not defin what "winning" is -- only you do. Yes, "scrub" playstyles can win the match but perhaps you're not trying to win the match but rather trying to win a loyal following or aclaim. Scrub playstyles, in these situations, may be sub-optimal. Play to win only requires you to identify the optimal strategies within the rule set, written or un-written, and employ those in pursuit of your goal.

* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:


