:PROPERTIES:
:ID:       3626303a-41d6-4d8c-98ee-186e6f59cb44
:DIR:      /home/cashweaver/proj/roam/attachments/3626303a-41d6-4d8c-98ee-186e6f59cb44
:ROAM_REFS: https://blog.samaltman.com/productivity
:END:
#+title: Productivity Notes from Sam Altman
#+hugo_custom_front_matter: roam_refs '("https://blog.samaltman.com/productivity")
#+filetags: :@Sam_Altman:productivity:meta-work:
#+author: Cash Weaver
#+date: [2021-12-03 Fri 08:43]
#+startup: overview
#+hugo_auto_set_lastmod: t

* Notes

#+begin_quote
It doesn't matter how fast you move if it's in a worthless direction. Picking the right thing to work on is the most important element of productivity and usually almost ignored.
#+end_quote

#+begin_quote
The most impressive people I know have strong beliefs about the world, which is rare in the general population. If you find yourself always agreeing with whomever you last spoke with, that's bad.
#+end_quote

#+begin_quote
I make sure to leave enough time in my schedule to think about what to work on. The best ways for me to do this are reading books, hanging out with interesting people, and spending time in nature.
#+end_quote

#+begin_quote
It's important to learn that you can learn anything you want, and that you can get better quickly. This feels like an unlikely miracle the first few times it happens, but eventually you learn to trust that you can do it.
#+end_quote

#+begin_quote
Doing great work usually requires colleagues of some sort. Try to be around smart, productive, happy, and positive people that don't belittle your ambitions. I love being around people who push me and inspire me to be better. To the degree you able to, avoid the opposite kind of people—the cost of letting them take up your mental cycles is horrific.
#+end_quote

#+begin_quote
You have to both pick the right problem and do the work. There aren't many shortcuts. If you're going to do something really important, you are very likely going to work both smart and hard.
#+end_quote

#+begin_quote
I highly recommend using lists. I make lists of what I want to accomplish each year, each month, and each day. Lists are very focusing, and they help me with multitasking because I don't have to keep as much in my head.
#+end_quote

#+begin_quote
don't fall into the trap of productivity porn— chasing productivity for its own sake isn't helpful. Many people spend too much time thinking about how to perfectly optimize their system, and not nearly enough asking if they're working on the right problems. It doesn't matter what system you use or if you squeeze out every second if you're working on the wrong thing.
#+end_quote

#+begin_quote
Like most people, I sometimes go through periods of a week or two where I just have no motivation to do anything (I suspect it may have something to do with nutrition). This sucks and always seems to happen at inconvenient times. I have not figured out what to do about it besides wait for the fog to lift, and to trust that eventually it always does. And I generally try to avoid people and situations that put me in bad moods, which is good advice whether you care about productivity or not.
#+end_quote

#+begin_quote
Don't neglect your family and friends for the sake of productivity—that's a very stupid tradeoff (and very likely a net productivity loss, because you'll be less happy). Don't neglect doing things you love or that clear your head either.
#+end_quote

* TODO Convert to citation
