:PROPERTIES:
:ID:       cf234015-e1ce-4689-97c8-e3848e435742
:END:
#+title: Season a cast iron skillet
#+author: Cash Weaver
#+date: [2022-06-21 Tue 18:51]
#+filetags: :concept:

#+begin_quote
The basic idea is this: Smear a food-grade drying oil onto a cast iron pan, and then bake it above the oil's smoke point. This will initiate the release of free radicals and polymerization. The more drying the oil, the harder the polymer. So start with the right oil.

[cite:@canterChemistryCastIron]
#+end_quote

1. Strip your pan down to the iron
2. Heat the pan to 200°F (94°C) to ensure it's dry
3. Pour a little flaxseed oil on the skillet and rub the oil all over with your hands
4. Wipe the skillet with a paper/cloth towel unitl it looks like there isn't any oil left (there is, just not a visible amount)
5. Place the skillet in the oven
6. Set the oven to bake at 500°F (260°C)
7. Leave the skillet in the oven for 1 hour after it reaches 500°F (260°C)
8. Turn the oven off
9. Leave the skillet in the oven for 2 hours and keep the door closed
10. Repeat 5 times so the skillet has a total of 6 coats


#+begin_quote
If you try this, you will be tempted to use a thicker coat of oil to speed up the process. Don't do it. It just gets you an uneven surface – or worse, baked on drips. Been there, done that. You can't speed up the process. If you try, you'll mess up the pan and have to start over.

[cite:@canterChemistryCastIron]
#+end_quote
#+print_bibliography:
* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:


