:PROPERTIES:
:ID:       4873ac61-c885-41f7-bbba-9269bc91b0a9
:END:
#+title: Secure attachment
#+author: Cash Weaver
#+date: [2022-06-26 Sun 11:35]
#+filetags: :concept:

An [[id:5f944538-ef8c-464f-b2da-c0f973558eca][attachment]] pattern in which the child ventures out into the world, encounters a Strange Situation, and returns to the guardian for comfort. The guardian provides the comfort the child seeks and this strengthens the child in future Strange Situations as they know they're supported and protected.

#+begin_quote
A toddler who is securely attached to his or her parent (or other familiar caregiver) will explore freely while the caregiver is present, typically engages with strangers, is often visibly upset when the caregiver departs, and is generally happy to see the caregiver return. The extent of exploration and of distress are affected, however, by the child's temperamental make-up and by situational factors as well as by attachment status. A child's attachment is largely influenced by their primary caregiver's sensitivity to their needs. Parents who consistently (or almost always) respond to their child's needs will create securely attached children. Such children are certain that their parents will be responsive to their needs and communications.

[cite:@AttachmentTheory2022]
#+end_quote

* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:

** Secure attachment
:PROPERTIES:
:ANKI_DECK: Default
:ANKI_NOTE_TYPE: Describe
:ANKI_NOTE_ID: 1656856964108
:END:
*** Context
Attachment theory

*** Description
A healthy attachment pattern between a child and their guardian(s) in which the child is able to encounter greater and greater Strange Situations, secure in the knowledge that they're supported and protected by their guardian(s).

*** Extra

*** Source
[cite:@AttachmentTheory2022]

** Secure attachment
:PROPERTIES:
:ANKI_NOTE_TYPE: Example(s)
:ANKI_NOTE_ID: 1656856964957
:END:

*** Example(s)
- A dog jumps up on a child. The child is scared and seeks comfort from their guardian(s). Their guardian(s) comfort and reassure them. The child is more resilient the next time a dog jumps up on them.

*** Extra

*** Source
[cite:@danskinEndnoteHowAltrightAbusiveRelationship2019]

#+print_bibliography:
