:PROPERTIES:
:ID:       246566c2-5b4b-479a-9e1d-522fd85903d9
:ROAM_ALIASES: "Speak past your opponent"
:END:
#+title: Speak directly to the audience
#+author: Cash Weaver
#+date: [2022-06-25 Sat 18:07]
#+filetags: :concept:

Consider a public argument between two individuals. There are three participants: the two individuals and the audience around them -- the public. It can be easier to win the argument, for some definitions of win, to speak past the person you're arguing with and instead talk directly to the audience; [[id:a6d989de-a309-479e-91ab-9327b8fdf874][ignore them altogether]].
* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:
** Speaking directly to the audience
:PROPERTIES:
:ANKI_DECK: Default
:ANKI_NOTE_TYPE: Describe
:ANKI_NOTE_ID: 1656856805258
:END:
*** Context
Argument, politics, community
*** Description
A technique which re-frames a discussion between yourself and another group to a discussion between yourself and the audience watching the first discussion. Implicitly redefines the goal of the original discussion from "Convince the person I'm arguing with of something" to "Convince the audience watching us of something", which is often a more correct goal than the former.
*** Extra
*** Source
