:PROPERTIES:
:ID:       05911fff-a79b-4462-bf6d-a3cec4e1c9f2
:DIR:      /home/cashweaver/proj/roam/attachments/05911fff-a79b-4462-bf6d-a3cec4e1c9f2
:END:
#+title: Style Guide
#+FILETAGS: :meta:
#+author: Cash Weaver
#+date: [2022-02-05 Sat 13:12]
#+startup: overview
#+hugo_auto_set_lastmod: t

A style guide for my [[id:773406e0-fe95-41f4-a254-b2c6ade18ce9][personal knowledge management]] system (powered by [[id:1497025f-da3e-4bed-be19-f8f9c9a0e351][org-roam]]):

* Tags

Prefer links to tags.

* Specifying an Author

Specify an author by linking to that author's node (eg: [[id:0d192773-9121-459e-931a-86a0f0ce9991][Cash Weaver]])

Formerly, the policy was: Specify an author using a node-level tag prefixed with =@= (eg: =@Cash_Weaver=).

* Quotes

** Attribution

Attribution lines in quotes should be in /italics/.

*** Does it Need Attribution?

Every quote should contain an attribution unless it meets one of the following criteria:

1. The quote is from a source referenced in =ROAM_REFS= and this source is the *only* source present in =ROAM_REFS=.

*** Examples

#+begin_quote
Org is a mode for keeping notes, maintaining TODO lists, and project planning with a fast and effective plain-text markup language. It also is an authoring system with unique support for literate programming and reproducible research.

/[[https://orgmode.org/manual/Summary.html][org-mode Manual: Summary]]/
#+end_quote

#+begin_quote
Muad'Dib learned rapidly because his first training was in how to learn. And the first lesson of all was the basic trust that he could learn. It's shocking to find how many people do not believe they can learn, and how many more believe learning to be difficult. Muad'Dib knew that every experience carries its lesson.

/Princess Irulan, [cite:@herbertDune1999]/
#+end_quote

** How Much is Too Much?

There isn't a hard rule on how much quoting is too much. Large quotes [[id:18745aec-fcd1-4dd5-a55f-73fdc409aacb][have their benefits]].

** Quote Nodes

Quotes should live in stand-alone single nodes (eg: [[id:7c49d995-a4d4-4c95-84c0-9dae9d8ab498][The First Lesson]]). This is multi-purpose:

1. When in doubt, make the node smaller.
2. Simplicity for the reader: Multiple quotes on a single page may confuse a user who has just arrived on that page by following a reference link. Which of the quotes they see is the right one?
3. Future-proof: We will be able to, eventually, provide hover previews (similar to those used on [[https://www.gwern.net/][gwern.net]]). Similarly, standalone quote nodes will fit into a transclusion model better than multi-quote nodes.
#+print_bibliography:

* Links

** Favicons

Favicons are nice additions to links. They provide visual context to where the user expects the link to take them. Let's include them alongside external links. I've written a [[https://github.com/cashweaver/basic-favicon-links][script to make the process easier]].

* Backlinks

Backlinks are the backbone of a powerful [[id:b130e6f2-31a1-4c3a-ae8b-7d8208a69710][zettelkasten]] system. The published form of these notes *must* include backlinks.
