:PROPERTIES:
:ID:       c3261b11-bf35-4ecd-b796-4157d766e7ed
:DIR:      /home/cashweaver/proj/roam/attachments/c3261b11-bf35-4ecd-b796-4157d766e7ed
:ROAM_REFS: https://www.theatlantic.com/magazine/archive/1919/11/the-basic-problem-of-democracy/569095/
:END:
#+TITLE: The Basic Problem of Democracy (1919)
#+hugo_custom_front_matter: roam_refs '("https://www.theatlantic.com/magazine/archive/1919/11/the-basic-problem-of-democracy/569095/")
#+STARTUP: overview
#+AUTHOR: Cash Weaver
#+DATE: [2021-12-27 Mon 23:10]
#+HUGO_AUTO_SET_LASTMOD: t
#+FILETAGS: :@Walter_Lippmann:

* Summary

A well written essay whose thesis, I'm a bit embarrassed to say, eludes me.

* Notes

#+begin_quote
If we substitute the word indifference for the word liberty, we shall come much closer to the real intention that lies behind the classic argument. Liberty is to be permitted where differences are of no great moment. It is this definition which has generally guided practice. In times when men feel themselves secure, heresy is cultivated as the spice of life. During a war liberty disappears as the as the community feels itself menaced. When revolution seems to be contagious, heresy-hunting is a respectable occupation. In other words, when men are not afraid, they are not afraid of ideas; when they are much afraid, they are afraid of anything that seems, or can even be made to appear, seditious. That is why nine tenths of the effort to live and let live consists in proving that the thing we wish to have tolerated is really a matter of indifference.
#+end_quote

* Thoughts

I expect one could find gold in this essay but I think I will instead read, as [[https://news.ycombinator.com/item?id=21896607][one commenter recommended]], "Goliath" by Matt Stoller.
