:PROPERTIES:
:ID:       47d61b82-dbf0-42b1-b612-3065af126e55
:DIR:      /home/cashweaver/proj/roam/attachments/47d61b82-dbf0-42b1-b612-3065af126e55
:ROAM_REFS: https://payne.org/blog/the-myth-of-the-myth-of-the-10x-programmer/
:END:
#+TITLE: The Myth of the Myth of the 10x Programmer
#+FILETAGS: :@Andy_Payne:meta-work:
#+hugo_custom_front_matter: roam_refs '("https://payne.org/blog/the-myth-of-the-myth-of-the-10x-programmer/")
#+STARTUP: overview
#+AUTHOR: Cash Weaver
#+DATE: [2021-12-31 Fri 17:30]
#+HUGO_AUTO_SET_LASTMOD: t

* Notes

#+begin_quote
I don’t know anyone 10x faster than their peers in solving well-defined programming problems.

...

[H]ighly productive developers (10x or otherwise) are problem-solving at a much higher level. Their productivity won’t be apparent from a narrow test, any more than the overall skill of a world-class football player would be apparent from (say) how fast they could run the 100m dash.

The most productive developers are solving big problems, and are bringing judgment and experience to bear on essential design, architecture, and “build vs use existing library” decisions. They’re designing key abstractions that will pay dividends through the life of the project. They’re finding massive shortcuts that aren’t in the CS textbook, such as Infocom’s use of a virtual machine to port their text adventure games to a range of early PC platforms. (Or, writing code to write CPU tests).

I think 10x developers, like world-class athletes, musicians, and authors, absolutely do exist. You’re just not going to find them with a coding test.
#+end_quote

* Thoughts

This reminds me of a way of conceptualizing a "10x" programmer (though I no longer recall where I read the idea): 10x programmers are not 10x because they code/write/etc 10x faster; they're 10x because they solve the big problems that a non-10x programmer cannot solve.
