:PROPERTIES:
:ID:       812da5d9-2917-4f0c-bf2f-36acf64af2c5
:DIR:      /home/cashweaver/proj/roam/attachments/812da5d9-2917-4f0c-bf2f-36acf64af2c5
:END:
#+title: This is Extremely Dangerous to Our Democracy
#+author: Cash Weaver
#+date: [2022-02-17 Thu 08:37]
#+filetags: :quote:

#+begin_quote
I'm extremely proud of the quality, balanced journalism that [proper news brand name of local station] produces. But I'm concerned about the troubling trend of irresponsible, one sided news stories plaguing our country. The sharing of biased and false news has become all too common on social media. More alarming, national media outlets are publishing these same fake stories without checking facts first. Unfortunately, some members of the national media are using their platforms to push their own personal bias and agenda to control 'exactly what people think'. *This is extremely dangerous to our democracy* ...  We understand Truth is neither politically 'left or right.' Our commitment to factual reporting is the foundation of our credibility, now more than ever.

[cite:@SinclairBroadcastingLocalNewsScript], [cite:@SinclairBroadcastGroup2022]
#+end_quote

#+print_bibliography:
* Anki :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:
