:PROPERTIES:
:ID:       548362c8-b5a6-4d50-b459-543d321e49b6
:DIR:      /home/cashweaver/proj/roam/attachments
:ROAM_REFS: https://blog.ycombinator.com/three-paths-in-the-tech-industry-founder-executive-or-employee/
:END:
#+title: Three Paths in the Tech Industry: Founder, Executive, or Employee
#+hugo_custom_front_matter: roam_refs '("https://blog.ycombinator.com/three-paths-in-the-tech-industry-founder-executive-or-employee/")
#+author: Cash Weaver
#+date: [2021-11-27 Thu 07:00]
#+hugo_draft: true

The article begins with:

#+begin_quote
I don’t attach value judgements to these three paths. In my ten years in The Bay Area I’ve seen friends lead successful and fulfilled lives following all three.
#+end_quote

I skipped over this point when I read this article for the first time in my haste to discover the details of the promised trio of paths. I'm currently an employee and feel at times that such a role is a mark of failure. It's easy for me to start thinking of what I do as not being "real" work.

Real work, in my mind, is unique. Real work is work which only a single person alive could accomplish. However, I think that I've built this idea on a flawed premise. Now that I think about it, I'm not convinced that people are as unique as I thought. It's a sobering idea.

---

I would define real work as work which no one else currently alive could accomplish which has "real" value to the world. I am not doing real work by this definition. Neither are any of my friends or peers. I have only encountered a small handful of people who I felt were /different/ in such a way that I felt they could accomplish something unique compared with others at their level. I find it disheartening to reflect on my work and decide that another could have done it as well or better than I have. It makes my accomplishments feel meaningless.

Another part of me isn't satisfied with this definition. "Real" work isn't the only kind of work out there. Say there's only one person who alive who could crack open some problem in a complicated field. That person wouldn't also be able to implement that solution across multiple domains, companies, etc. Those implementations of a burst of "real" work are valuable and meaningful. The person who discovers a new irrigation method has done meaningful work but so have the people who put that discovery into practice in farms around the world.

Perhaps the nuance I'm attempting to address is somewhere between meaningful work and unique work.

* TODO Convert to citation
