:PROPERTIES:
:ID:       9bbe0740-9dff-4d2a-908e-535e96ea4e59
:DIR:      /home/cashweaver/proj/roam/attachments/9bbe0740-9dff-4d2a-908e-535e96ea4e59
:ROAM_REFS: https://www.lesswrong.com/posts/DoLQN5ryZ9XkZjq5h/tsuyoku-naritai-i-want-to-become-stronger
:END:
#+title: Tsuyoku Naritai (I Want to Become Stronger)
#+hugo_custom_front_matter: roam_refs '("https://www.lesswrong.com/posts/DoLQN5ryZ9XkZjq5h/tsuyoku-naritai-i-want-to-become-stronger")
#+filetags: :@Eliezer_Yudkowsky:
#+author: Cash Weaver
#+date: [2021-12-03 Fri 12:43]
#+startup: overview
#+hugo_auto_set_lastmod: t

#+begin_quote
The most important thing is that there should be progress. So long as you keep moving forward you will reach your destination; but if you stop moving you will never reach it.

Tsuyoku naritai is Japanese. Tsuyoku is “strong”; naru is “becoming,” and the form naritai is “want to become.” Together it means, “I want to become stronger,” and it expresses a sentiment embodied more intensely in Japanese works than in any Western literature I’ve read. You might say it when expressing your determination to become a professional Go player—or after you lose an important match, but you haven’t given up—or after you win an important match, but you’re not a ninth-dan player yet—or after you’ve become the greatest Go player of all time, but you still think you can do better. That is tsuyoku naritai, the will to transcendence.
#+end_quote

#+begin_quote
Take no pride in your confession that you too are biased; do not glory in your self-awareness of your flaws. This is akin to the principle of not taking pride in confessing your ignorance; for if your ignorance is a source of pride to you, you may become loath to relinquish your ignorance when evidence comes knocking. Likewise with our flaws—we should not gloat over how self-aware we are for confessing them; the occasion for rejoicing is when we have a little less to confess.

...

Never confess to me that you are just as flawed as I am unless you can tell me what you plan to do about it. Afterward you will still have plenty of flaws left, but that’s not the point; the important thing is to do better, to keep moving ahead, to take one more step forward. Tsuyoku naritai!
#+end_quote

* TODO Convert to citation
